type                = "directrequest"
schemaVersion       = 1
name                = "Get PULA Yield Data V2"
contractAddress     = "0x7178a8Cad2fa94ff308c5dD5Aba4dbe3393D3c47"
observationSource   = """
"""
