name: Events

on: 
  workflow_dispatch:
  push:
    branches: [ master ]
    tags:
    - '*'
  pull_request:

jobs:
  inspect:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate events
        run: .github/workflows/scripts/validate_events.sh
      

