name: Run tests with code coverage

on: 
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Setup node environment
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Download required solidity compilers
        run: mkdir -p ~/.solcx/ && wget -O ~/.solcx/solc-v0.7.2 https://binaries.soliditylang.org/linux-amd64/solc-linux-amd64-v0.7.2+commit.51b20bc0
      - run: wget -O ~/.solcx/solc-v0.8.2 https://binaries.soliditylang.org/linux-amd64/solc-linux-amd64-v0.8.2+commit.661d1103 
      - run: wget -O ~/.solcx/solc-v0.8.15 https://binaries.soliditylang.org/linux-amd64/solc-linux-amd64-v0.8.15+commit.e14f2714
      - run: chmod 755 ~/.solcx/solc*

      - name: Install ganache
        run: npm install --global ganache-cli

      - name: Setup brownie
        run: wget https://raw.githubusercontent.com/eth-brownie/brownie/master/requirements.txt
      - run: pip install -r requirements.txt 
      - run: pip install eth-brownie 

      - name: Compile contracts
        run: brownie compile --all
      - run: touch .env
      - name: Execute tests
        run: brownie test -C
        
      - name: Archive test report artifacts
        uses: actions/upload-artifact@v3
        with:
          name: reports
          path: |
            reports